# permissions for end users to view servicerunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicerunner-viewer-role
rules:
- apiGroups:
  - servicecatalog.io.servicecatalog.io
  resources:
  - servicerunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicecatalog.io.servicecatalog.io
  resources:
  - servicerunners/status
  verbs:
  - get
