//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Red Hat.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRunner) DeepCopyInto(out *ServiceRunner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRunner.
func (in *ServiceRunner) DeepCopy() *ServiceRunner {
	if in == nil {
		return nil
	}
	out := new(ServiceRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceRunner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRunnerBindingRef) DeepCopyInto(out *ServiceRunnerBindingRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRunnerBindingRef.
func (in *ServiceRunnerBindingRef) DeepCopy() *ServiceRunnerBindingRef {
	if in == nil {
		return nil
	}
	out := new(ServiceRunnerBindingRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRunnerImage) DeepCopyInto(out *ServiceRunnerImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRunnerImage.
func (in *ServiceRunnerImage) DeepCopy() *ServiceRunnerImage {
	if in == nil {
		return nil
	}
	out := new(ServiceRunnerImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRunnerList) DeepCopyInto(out *ServiceRunnerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceRunner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRunnerList.
func (in *ServiceRunnerList) DeepCopy() *ServiceRunnerList {
	if in == nil {
		return nil
	}
	out := new(ServiceRunnerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceRunnerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRunnerSpec) DeepCopyInto(out *ServiceRunnerSpec) {
	*out = *in
	if in.ServiceParam != nil {
		in, out := &in.ServiceParam, &out.ServiceParam
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ServiceImage = in.ServiceImage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRunnerSpec.
func (in *ServiceRunnerSpec) DeepCopy() *ServiceRunnerSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRunnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRunnerStatus) DeepCopyInto(out *ServiceRunnerStatus) {
	*out = *in
	if in.Binding != nil {
		in, out := &in.Binding, &out.Binding
		*out = new(ServiceRunnerBindingRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRunnerStatus.
func (in *ServiceRunnerStatus) DeepCopy() *ServiceRunnerStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceRunnerStatus)
	in.DeepCopyInto(out)
	return out
}
